// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Default: typeof import("./layouts/default.vue")["default"];
    ErrorNotFound: typeof import("./pages/ErrorNotFound.vue")["default"];
    EssentialLink: typeof import("./components/EssentialLink.vue")["default"];
    Home: typeof import("./pages/Home.vue")["default"];
    MainLayout: typeof import("./layouts/MainLayout.vue")["default"];
    MyButton: typeof import("./components/MyButton.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Test: typeof import("./pages/Test.vue")["default"];
    TestLayout: typeof import("./layouts/TestLayout.vue")["default"];
  }
}

export {};
